export const Races = [
  // 2023
  {
    grandPrix: "Bahrain",
    date: "05 Mar 2023",
    winner: "Max Verstappen",
    car: "RED BULL RACING HONDA RBPT",
    laps: 57,
    time: "1:33:56.736",
    drivers: [
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING HONDA RBPT",
        laps: 57,
        time: "1:33:56.736",
        PTS: 25,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 57,
        time: "+72.647s",
        PTS: 4,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 57,
        time: "+50.977s",
        PTS: 10,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 57,
        time: "+48.052s",
        PTS: 12,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING HONDA RBPT",
        laps: 57,
        time: "+11.987s",
        PTS: 18,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 57,
        time: "+89.774s",
        PTS: 1,
      },
    ],
  },
  {
    grandPrix: "Saudi Arabia",
    date: "19 Mar 2023",
    winner: "Sergio Perez",
    car: "RED BULL RACING HONDA RBPT",
    laps: 50,
    time: "1:21:14.894",
    drivers: [
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING HONDA RBPT",
        laps: 50,
        time: "1:21:14.894",
        PTS: 25,
      },
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING HONDA RBPT",
        laps: 50,
        time: "+5.355s",
        PTS: 19,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 50,
        time: "+31.065s",
        PTS: 10,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 50,
        time: "+35.876s",
        PTS: 8,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 27,
        time: "DNF",
        PTS: 0,
      },
    ],
  },
  {
    grandPrix: "Australia",
    date: "02 Apr 2023",
    winner: "Max Verstappen",
    car: "RED BULL RACING HONDA RBPT",
    laps: 58,
    time: "2:32:38.371",
    drivers: [
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING HONDA RBPT",
        laps: 58,
        time: "2:32:38.371",
        PTS: 25,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 58,
        time: "+0.179s",
        PTS: 18,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING HONDA RBPT",
        laps: 58,
        time: "+3.320s",
        PTS: 11,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 58,
        time: "+6.513s",
        PTS: 0,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 55,
        time: "+6.594s",
        PTS: 0,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 23,
        time: "DNF",
        PTS: 0,
      },
    ],
  },
  {
    grandPrix: "Azerbaijan",
    date: "30 Apr 2023",
    winner: "Sergio Perez",
    car: "RED BULL RACING HONDA RBPT",
    laps: 51,
    time: "1:32:42.436",
    drivers: [
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING HONDA RBPT",
        laps: 51,
        time: "1:32:42.436",
        PTS: 25,
      },
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING HONDA RBPT",
        laps: 51,
        time: "+2.137s",
        PTS: 18,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 51,
        time: "+45.491s",
        PTS: 10,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 51,
        time: "+46.145s",
        PTS: 8,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 51,
        time: "+88.623s",
        PTS: 0,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 50,
        time: "+1 lap",
        PTS: 0,
      },
    ],
  },
  {
    grandPrix: "Miami",
    date: "07 May 2023",
    winner: "Max Verstappen",
    car: "RED BULL RACING HONDA RBPT",
    laps: 57,
    time: "1:27:38.241",
    drivers: [
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING HONDA RBPT",
        laps: 57,
        time: "1:27:38.241",
        PTS: 26,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING HONDA RBPT",
        laps: 57,
        time: "+5.384s",
        PTS: 18,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 57,
        time: "+42.511s",
        PTS: 10,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 57,
        time: "+51.249s",
        PTS: 8,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 57,
        time: "+71.637s",
        PTS: 0,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 57,
        time: "+72.861s",
        PTS: 0,
      },
    ],
  },
  {
    grandPrix: "Monaco",
    date: "28 May 2023",
    winner: "Max Verstappen",
    car: "RED BULL RACING HONDA RBPT",
    laps: 78,
    time: "1:48:51.980",
    drivers: [
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING HONDA RBPT",
        laps: 78,
        time: "1:48:51.980",
        PTS: 25,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 78,
        time: "+39.062s",
        PTS: 13,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 78,
        time: "+63.391s",
        PTS: 4,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 77,
        time: "+1 lap",
        PTS: 0,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 77,
        time: "+1 lap",
        PTS: 0,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING HONDA RBPT",
        laps: 76,
        time: "+2 laps",
        PTS: 0,
      },
    ],
  },
  {
    grandPrix: "Spain",
    date: "04 Jun 2023",
    winner: "Max Verstappen",
    car: "RED BULL RACING HONDA RBPT",
    laps: 66,
    time: "1:27:57.940",
    drivers: [
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING HONDA RBPT",
        laps: 66,
        time: "1:27:57.940",
        PTS: 26,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 66,
        time: "+24.090s",
        PTS: 18,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING HONDA RBPT",
        laps: 66,
        time: "+35.812s",
        PTS: 12,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 66,
        time: "+45.698s",
        PTS: 10,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 65,
        time: "+1 lap",
        PTS: 0,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 65,
        time: "+1 lap",
        PTS: 0,
      },
    ],
  },
  // 2022
  {
    grandPrix: "Saudi Arabia",
    date: "27 Mar 2022",
    winner: "Max Verstappen",
    car: "RED BULL RACING RBPT",
    laps: 50,
    time: "1:24:19.293",
    drivers: [
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 50,
        time: "1:24:19.293",
        PTS: 25,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 50,
        time: "+8.097s",
        PTS: 15,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 50,
        time: "+10.800s",
        PTS: 12,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 50,
        time: "+73.948s",
        PTS: 1,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 36,
        time: "DNF",
        PTS: 0,
      },
    ],
  },
  {
    grandPrix: "Bahrain",
    date: "20 Mar 2022",
    winner: "Charles Leclerc",
    car: "FERRARI",
    laps: 57,
    time: "1:37:33.584",
    drivers: [
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 57,
        time: "1:37:33.584",
        PTS: 18,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 57,
        time: "+9.675s",
        PTS: 15,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 57,
        time: "+16.119s",
        PTS: 8,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 56,
        time: "DNF",
        PTS: 0,
      },
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 54,
        time: "DNF",
        PTS: 0,
      },
    ],
  },
  {
    grandPrix: "Australia",
    date: "10 Apr 2022",
    winner: "Charles Leclerc",
    car: "FERRARI",
    laps: 58,
    time: "1:27:46.548",
    drivers: [
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 58,
        time: "1:27:46.548",
        PTS: 26,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 58,
        time: "+28.543s",
        PTS: 12,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 58,
        time: "+68.439s",
        PTS: 4,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 58,
        time: "+79.382s",
        PTS: 1,
      },
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 38,
        time: "DNF",
        PTS: 0,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 57,
        time: "DNF",
        PTS: 0,
      },
    ],
  },
  {
    grandPrix: "Emilia Romagna",
    date: "24 Apr 2022",
    winner: "Max Verstappen",
    car: "RED BULL RACING RBPT",
    laps: 63,
    time: "1:32:07.986",
    drivers: [
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 63,
        time: "1:32:07.986",
        PTS: 26,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 63,
        time: "+16.527s",
        PTS: 18,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 63,
        time: "+43.181s",
        PTS: 10,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 62,
        time: "+1 lap",
        PTS: 0,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 62,
        time: "+1 lap",
        PTS: 0,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 0,
        time: "DNF",
        PTS: 0,
      },
    ],
  },
  {
    grandPrix: "Miami",
    date: "08 May 2022",
    winner: "Max Verstappen",
    car: "RED BULL RACING RBPT",
    laps: 57,
    time: "1:34:24.258",
    drivers: [
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 57,
        time: "1:34:24.258",
        PTS: 26,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 57,
        time: "+8.229s",
        PTS: 15,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 57,
        time: "+10.638s",
        PTS: 12,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 57,
        time: "+21.368s",
        PTS: 8,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 57,
        time: "+25.073s",
        PTS: 6,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 57,
        time: "+32.365s",
        PTS: 2,
      },
    ],
  },
  // 2021
  {
    grandPrix: "Bahrain",
    date: "28 Mar 2021",
    winner: "Lewis Hamilton",
    car: "MERCEDES",
    laps: 56,
    time: "1:32:03.897",
    drivers: [
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 56,
        time: "1:32:03.897",
        PTS: 26,
      },
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 56,
        time: "+5.285s",
        PTS: 18,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 56,
        time: "+8.229s",
        PTS: 15,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 56,
        time: "+10.638s",
        PTS: 12,
      },

      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 56,
        time: "+25.073s",
        PTS: 6,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 56,
        time: "+32.365s",
        PTS: 2,
      },
    ],
  },
  {
    grandPrix: "Emilia Romagna",
    date: "18 Apr 2021",
    winner: "Max Verstappen",
    car: "RED BULL RACING HONDA",
    laps: 63,
    time: "2:02:34.598",
    drivers: [
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 63,
        time: "2:02:34.598",
        PTS: 26,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 63,
        time: "+8.229s",
        PTS: 15,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 63,
        time: "+10.638s",
        PTS: 12,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 63,
        time: "+21.368s",
        PTS: 8,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 63,
        time: "+25.073s",
        PTS: 6,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 63,
        time: "+32.365s",
        PTS: 2,
      },
    ],
  },
  {
    grandPrix: "Portugal",
    date: "02 May 2021",
    winner: "Lewis Hamilton",
    car: "MERCEDES",
    laps: 66,
    time: "1:34:31.421",
    drivers: [
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 66,
        time: "1:34:31.421",
        PTS: 25,
      },
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 66,
        time: "+1.822s",
        PTS: 18,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 66,
        time: "+8.229s",
        PTS: 15,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 66,
        time: "+10.638s",
        PTS: 12,
      },

      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 66,
        time: "+25.073s",
        PTS: 6,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 66,
        time: "+32.365s",
        PTS: 2,
      },
    ],
  },
  {
    grandPrix: "Spain",
    date: "09 May 2021",
    winner: "Lewis Hamilton",
    car: "MERCEDES",
    laps: 66,
    time: "1:33:07.680",
    drivers: [
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 66,
        time: "1:33:07.680",
        PTS: 26,
      },
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 66,
        time: "+8.2s",
        PTS: 18,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 66,
        time: "+8.229s",
        PTS: 15,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 66,
        time: "+10.638s",
        PTS: 12,
      },

      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 66,
        time: "+25.073s",
        PTS: 6,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 66,
        time: "+32.365s",
        PTS: 2,
      },
    ],
  },
  {
    grandPrix: "Monaco",
    date: "23 May 2021",
    winner: "Max Verstappen",
    car: "RED BULL RACING HONDA",
    laps: 78,
    time: "1:38:56.820",
    drivers: [
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 78,
        time: "1:34:24.258",
        PTS: 26,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 78,
        time: "+8.229s",
        PTS: 15,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 78,
        time: "+10.638s",
        PTS: 12,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 78,
        time: "+21.368s",
        PTS: 8,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 78,
        time: "+25.073s",
        PTS: 6,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 78,
        time: "+32.365s",
        PTS: 2,
      },
    ],
  },
  // 2020
  {
    grandPrix: "Austria",
    date: "05 Jul 2020",
    winner: "Valtteri Bottas",
    car: "MERCEDES",
    laps: 71,
    time: "1:30:55.739",
    drivers: [
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 71,
        time: "1:30:55.739",
        PTS: 26,
      },
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 71,
        time: "+3.333s",
        PTS: 18,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 71,
        time: "+8.229s",
        PTS: 15,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 71,
        time: "+10.638s",
        PTS: 12,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 71,
        time: "+21.368s",
        PTS: 8,
      },

      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 71,
        time: "+32.365s",
        PTS: 2,
      },
    ],
  },
  {
    grandPrix: "Styria",
    date: "12 Jul 2020",
    winner: "Lewis Hamilton",
    car: "MERCEDES",
    laps: 71,
    time: "1:22:50.683",
    drivers: [
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 71,
        time: "1:22:50.683",
        PTS: 26,
      },
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 71,
        time: "+5.683s",
        PTS: 18,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 71,
        time: "+8.229s",
        PTS: 15,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 71,
        time: "+10.638s",
        PTS: 12,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 71,
        time: "+21.368s",
        PTS: 8,
      },

      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 71,
        time: "+32.365s",
        PTS: 2,
      },
    ],
  },
  {
    grandPrix: "70th Anniversary",
    date: "09 Aug 2020",
    winner: "Max Verstappen",
    car: "RED BULL RACING HONDA",
    laps: 52,
    time: "1:19:41.993",
    drivers: [
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 52,
        time: "1:19:41.993",
        PTS: 26,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 52,
        time: "+5.739s",
        PTS: 18,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 52,
        time: "+8.229s",
        PTS: 15,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 52,
        time: "+10.638s",
        PTS: 12,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 52,
        time: "+21.368s",
        PTS: 8,
      },

      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 52,
        time: "+32.365s",
        PTS: 2,
      },
    ],
  },
  // 2019
  {
    grandPrix: "Bahrain",
    date: "31 Mar 2019",
    winner: "Lewis Hamilton",
    car: "MERCEDES",
    laps: 57,
    time: "1:34:21.295",
    drivers: [
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 57,
        time: "1:34:21.295",
        PTS: 26,
      },
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 57,
        time: "+1.993s",
        PTS: 18,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 57,
        time: "+5.739s",
        PTS: 18,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 57,
        time: "+8.229s",
        PTS: 15,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 57,
        time: "+10.638s",
        PTS: 12,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 57,
        time: "+32.365s",
        PTS: 2,
      },
    ],
  },
  {
    grandPrix: "China",
    date: "14 Apr 2019",
    winner: "Lewis Hamilton",
    car: "MERCEDES",
    laps: 56,
    time: "1:32:06.350",
    drivers: [
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 56,
        time: "1:32:06.350",
        PTS: 26,
      },
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 56,
        time: "+1.993s",
        PTS: 18,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 56,
        time: "+5.739s",
        PTS: 18,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 56,
        time: "+8.229s",
        PTS: 15,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 56,
        time: "+10.638s",
        PTS: 12,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 56,
        time: "+32.365s",
        PTS: 2,
      },
    ],
  },
  {
    grandPrix: "Azerbaijan",
    date: "28 Apr 2019",
    winner: "Valtteri Bottas",
    car: "MERCEDES",
    laps: 51,
    time: "1:31:52.942",
    drivers: [
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 51,
        time: "1:31:52.942",
        PTS: 26,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 51,
        time: "+2.295s",
        PTS: 18,
      },
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 51,
        time: "+1.993s",
        PTS: 18,
      },

      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 51,
        time: "+8.229s",
        PTS: 15,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 51,
        time: "+10.638s",
        PTS: 12,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 51,
        time: "+32.365s",
        PTS: 2,
      },
    ],
  },
  // 2018
  {
    grandPrix: "Austria",
    date: "01 Jul 2018",
    winner: "Max Verstappen",
    car: "RED BULL RACING TAG HEUER",
    laps: 71,
    time: "1:21:56.024",
    drivers: [
      {
        driver: "Max Verstappen",
        no: 77,
        car: "RED BULL RACING TAG HEUER",
        laps: 71,
        time: "1:21:56.024",
        PTS: 26,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 71,
        time: "+2.295s",
        PTS: 18,
      },
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 71,
        time: "+1.993s",
        PTS: 18,
      },

      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 71,
        time: "+8.229s",
        PTS: 15,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 71,
        time: "+10.638s",
        PTS: 12,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 71,
        time: "+32.365s",
        PTS: 2,
      },
    ],
  },
  {
    grandPrix: "Brazil",
    date: "11 Nov 2018",
    winner: "Lewis Hamilton",
    car: "MERCEDES",
    laps: 71,
    time: "1:27:09.066",
    drivers: [
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 51,
        time: "1:27:09.066",
        PTS: 26,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 51,
        time: "+2.942s",
        PTS: 18,
      },
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 51,
        time: "+1.993s",
        PTS: 18,
      },
      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 51,
        time: "+8.229s",
        PTS: 15,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 51,
        time: "+10.638s",
        PTS: 12,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 51,
        time: "+32.365s",
        PTS: 2,
      },
    ],
  },
  {
    grandPrix: "Abu Dhabi",
    date: "25 Nov 2018",
    winner: "Lewis Hamilton",
    car: "MERCEDES",
    laps: 55,
    time: "1:39:40.382",
    drivers: [
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 55,
        time: "1:39:40.382",
        PTS: 26,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 55,
        time: "+2.942s",
        PTS: 18,
      },
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 55,
        time: "+1.993s",
        PTS: 18,
      },

      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 55,
        time: "+8.229s",
        PTS: 15,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 55,
        time: "+10.638s",
        PTS: 12,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 55,
        time: "+32.365s",
        PTS: 2,
      },
    ],
  },
  // 2017
  {
    grandPrix: "China",
    date: "09 Apr 2017",
    winner: "Lewis Hamilton",
    car: "MERCEDES",
    laps: 56,
    time: "1:37:36.158",
    drivers: [
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 56,
        time: "1:37:36.158",
        PTS: 26,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 56,
        time: "+2.942s",
        PTS: 18,
      },
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 56,
        time: "+1.993s",
        PTS: 18,
      },

      {
        driver: "Carlos Sainz",
        no: 56,
        car: "FERRARI",
        laps: 56,
        time: "+8.229s",
        PTS: 15,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 56,
        time: "+10.638s",
        PTS: 12,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 56,
        time: "+32.365s",
        PTS: 2,
      },
    ],
  },
  {
    grandPrix: "Russia",
    date: "30 Apr 2017",
    winner: "Valtteri Bottas",
    car: "MERCEDES",
    laps: 52,
    time: "1:28:08.743",
    drivers: [
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 52,
        time: "1:28:08.743",
        PTS: 26,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 52,
        time: "+0.382s",
        PTS: 18,
      },
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING RBPT",
        laps: 52,
        time: "+1.993s",
        PTS: 18,
      },

      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 52,
        time: "+8.229s",
        PTS: 15,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 52,
        time: "+10.638s",
        PTS: 12,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 52,
        time: "+32.365s",
        PTS: 2,
      },
    ],
  },
  {
    grandPrix: "Mexico",
    date: "29 Oct 2017",
    winner: "Max Verstappen",
    car: "RED BULL RACING TAG HEUER",
    laps: 71,
    time: "1:36:26.552",
    drivers: [
      {
        driver: "Max Verstappen",
        no: 1,
        car: "RED BULL RACING TAG HEUER",
        laps: 71,
        time: "1:36:26.552",
        PTS: 26,
      },
      {
        driver: "Lewis Hamilton",
        no: 44,
        car: "MERCEDES",
        laps: 71,
        time: "+1.382s",
        PTS: 18,
      },
      {
        driver: "Valtteri Bottas",
        no: 77,
        car: "ALFA ROMEO FERRARI",
        laps: 71,
        time: "+2.942s",
        PTS: 16,
      },

      {
        driver: "Carlos Sainz",
        no: 55,
        car: "FERRARI",
        laps: 71,
        time: "+8.229s",
        PTS: 15,
      },
      {
        driver: "Sergio Perez",
        no: 11,
        car: "RED BULL RACING RBPT",
        laps: 71,
        time: "+10.638s",
        PTS: 12,
      },
      {
        driver: "Alexander Albon",
        no: 23,
        car: "WILLIAMS MERCEDES",
        laps: 71,
        time: "+32.365s",
        PTS: 2,
      },
    ],
  },
];

export const Driver = [
  {
    name: "Alexander Albon",
    nationality: "THA",
    matchs: [
      {
        grandPrix: "Australia",
        team: "WILLIAMS MERCEDES",
        date: "02 Apr 2023",
        racePosition: "DNF",
        PTS: 0,
      },
      {
        grandPrix: "Azerbaijan",
        team: "WILLIAMS MERCEDES",
        date: "30 Apr 2023",
        racePosition: 12,
        PTS: 0,
      },
      {
        grandPrix: "Miami",
        team: "WILLIAMS MERCEDES",
        date: "07 May 2023",
        racePosition: 14,
        PTS: 0,
      },
      {
        grandPrix: "Monaco",
        team: "WILLIAMS MERCEDES",
        date: "28 May 2023",
        racePosition: 14,
        PTS: 0,
      },
      {
        grandPrix: "Bahrain",
        team: "WILLIAMS MERCEDES",
        date: "05 Mar 2023",
        racePosition: 10,
        PTS: 1,
      },
      {
        grandPrix: "Saudi Arabia",
        team: "WILLIAMS MERCEDES",
        date: "19 Mar 2023",
        racePosition: "DNF",
        PTS: 0,
      },
      {
        grandPrix: "Spain",
        team: "WILLIAMS MERCEDES",
        date: "04 Jun 2023",
        racePosition: 16,
        PTS: 0,
      },

      {
        grandPrix: "Australia",
        team: "WILLIAMS MERCEDES",
        date: "	10 Apr 2022",
        racePosition: 10,
        PTS: 1,
      },
      {
        grandPrix: "Miami",
        team: "WILLIAMS MERCEDES",
        date: "08 May 2022",
        racePosition: 9,
        PTS: 2,
      },
      {
        grandPrix: "Monaco",
        team: "WILLIAMS MERCEDES",
        date: "29 May 2022",
        racePosition: "DNF",
        PTS: 0,
      },
      {
        grandPrix: "Bahrain",
        team: "RED BULL RACING HONDA",
        date: "29 Nov 2020",
        racePosition: 3,
        PTS: 15,
      },
      {
        grandPrix: "Hungary",
        team: "RED BULL RACING HONDA",
        date: "19 Jul 2020",
        racePosition: 5,
        PTS: 10,
      },
      {
        grandPrix: "Monaco",
        team: "SCUDERIA TORO ROSSO HONDA",
        date: "26 May 2019",
        racePosition: 8,
        PTS: 4,
      },
      {
        grandPrix: "Austria",
        team: "SCUDERIA TORO ROSSO HONDA",
        date: "30 Jun 2019",
        racePosition: 15,
        PTS: 0,
      },
      {
        grandPrix: "France",
        team: "SCUDERIA TORO ROSSO HONDA",
        date: "	23 Jun 2019",
        racePosition: 15,
        PTS: 0,
      },
    ],
  },
  {
    name: "Valtteri Bottas",
    nationality: "FIN",
    matchs: [
      {
        grandPrix: "Bahrain",
        team: "ALFA ROMEO FERRARI",
        date: "05 Mar 2023",
        racePosition: 8,
        PTS: 4,
      },
      {
        grandPrix: "Saudi Arabia",
        team: "ALFA ROMEO FERRARI",
        date: "19 Mar 2023",
        racePosition: 18,
        PTS: 0,
      },
      {
        grandPrix: "Australia",
        team: "ALFA ROMEO FERRARI",
        date: "02 Apr 2023",
        racePosition: 11,
        PTS: 0,
      },
      {
        grandPrix: "Azerbaijan",
        team: "ALFA ROMEO FERRARI",
        date: "30 Apr 2023",
        racePosition: 18,
        PTS: 0,
      },
      {
        grandPrix: "Miami",
        team: "ALFA ROMEO FERRARI",
        date: "07 May 2023",
        racePosition: 13,
        PTS: 0,
      },
      {
        grandPrix: "Monaco",
        team: "ALFA ROMEO FERRARI",
        date: "28 May 2023",
        racePosition: 11,
        PTS: 0,
      },
      {
        grandPrix: "Spain",
        team: "ALFA ROMEO FERRARI",
        date: "04 Jun 2023",
        racePosition: 19,
        PTS: 0,
      },
      {
        grandPrix: "Bahrain",
        team: "ALFA ROMEO FERRARI",
        date: "20 Mar 2022",
        racePosition: 6,
        PTS: 8,
      },
      {
        grandPrix: "Saudi Arabia",
        team: "ALFA ROMEO FERRARI",
        date: "27 Mar 2022",
        racePosition: "DNF",
        PTS: 0,
      },
      {
        grandPrix: "Australia",
        team: "ALFA ROMEO FERRARI",
        date: "10 Apr 2022",
        racePosition: 8,
        PTS: 4,
      },
      {
        grandPrix: "Emilia Romagna",
        team: "ALFA ROMEO FERRARI",
        date: "24 Apr 2022",
        racePosition: 5,
        PTS: 12,
      },
      {
        grandPrix: "Turkey",
        team: "MERCEDES",
        date: "10 Oct 2021",
        racePosition: 1,
        PTS: 26,
      },
      {
        grandPrix: "United States",
        team: "MERCEDES",
        date: "24 Oct 2021",
        racePosition: 6,
        PTS: 8,
      },
      {
        grandPrix: "Mexico",
        team: "MERCEDES",
        date: "07 Nov 2021",
        racePosition: 15,
        PTS: 0,
      },
      {
        grandPrix: "Bahrain",
        team: "MERCEDES",
        date: "29 Nov 2020",
        racePosition: 8,
        PTS: 4,
      },
      {
        grandPrix: "Belgium",
        team: "MERCEDES",
        date: "30 Aug 2020",
        racePosition: 2,
        PTS: 18,
      },
      {
        grandPrix: "Australia",
        team: "MERCEDES",
        date: "17 Mar 2019",
        racePosition: 1,
        PTS: 26,
      },
      {
        grandPrix: "China",
        team: "MERCEDES",
        date: "14 Apr 2019",
        racePosition: 2,
        PTS: 18,
      },
      {
        grandPrix: "Russia",
        team: "MERCEDES",
        date: "30 Sep 2018",
        racePosition: 2,
        PTS: 18,
      },
      {
        grandPrix: "Japan",
        team: "MERCEDES",
        date: "07 Oct 2018",
        racePosition: 2,
        PTS: 18,
      },
      {
        grandPrix: "Russia",
        team: "MERCEDES",
        date: "30 Apr 2017",
        racePosition: 1,
        PTS: 25,
      },
      {
        grandPrix: "Spain",
        team: "MERCEDES",
        date: "14 May 2017",
        racePosition: "DNF",
        PTS: 0,
      },
    ],
  },
  {
    name: "Max Verstappen",
    nationality: "NED",
    matchs: [
      {
        grandPrix: "Bahrain",
        team: "RED BULL RACING HONDA RBPT",
        date: "05 Mar 2023",
        racePosition: 1,
        PTS: 25,
      },
      {
        grandPrix: "Saudi Arabia",
        team: "RED BULL RACING HONDA RBPT",
        date: "19 Mar 2023",
        racePosition: 2,
        PTS: 19,
      },
      {
        grandPrix: "Australia",
        team: "RED BULL RACING HONDA RBPT",
        date: "02 Apr 2023",
        racePosition: 1,
        PTS: 25,
      },
      {
        grandPrix: "Azerbaijan",
        team: "RED BULL RACING HONDA RBPT",
        date: "30 Apr 2023",
        racePosition: 2,
        PTS: 24,
      },
      {
        grandPrix: "Miami",
        team: "RED BULL RACING HONDA RBPT",
        date: "07 May 2023",
        racePosition: 1,
        PTS: 26,
      },
      {
        grandPrix: "Monaco",
        team: "RED BULL RACING HONDA RBPT",
        date: "28 May 2023",
        racePosition: 1,
        PTS: 25,
      },
      {
        grandPrix: "Spain",
        team: "RED BULL RACING HONDA RBPT",
        date: "04 Jun 2023",
        racePosition: 1,
        PTS: 25,
      },
      {
        grandPrix: "Bahrain",
        team: "RED BULL RACING RBPT",
        date: "20 Mar 2022",
        racePosition: "DNF",
        PTS: 0,
      },
      {
        grandPrix: "Saudi Arabia",
        team: "RED BULL RACING RBPT",
        date: "27 Mar 2022",
        racePosition: 1,
        PTS: 25,
      },
      {
        grandPrix: "Australia",
        team: "RED BULL RACING RBPT",
        date: "10 Apr 2022",
        racePosition: "DNF",
        PTS: 0,
      },
      {
        grandPrix: "Emilia Romagna",
        team: "RED BULL RACING RBPT",
        date: "24 Apr 2022",
        racePosition: 1,
        PTS: 34,
      },
      {
        grandPrix: "Turkey",
        team: "RED BULL RACING HONDA",
        date: "10 Oct 2021",
        racePosition: 2,
        PTS: 18,
      },
      {
        grandPrix: "United States",
        team: "RED BULL RACING HONDA",
        date: "24 Oct 2021",
        racePosition: 1,
        PTS: 25,
      },
      {
        grandPrix: "Mexico",
        team: "RED BULL RACING HONDA",
        date: "07 Nov 2021",
        racePosition: 1,
        PTS: 25,
      },
      {
        grandPrix: "Bahrain",
        team: "RED BULL RACING HONDA",
        date: "29 Nov 2020",
        racePosition: 2,
        PTS: 19,
      },
      {
        grandPrix: "Belgium",
        team: "RED BULL RACING HONDA",
        date: "30 Aug 2020",
        racePosition: 3,
        PTS: 15,
      },
      {
        grandPrix: "Australia",
        team: "RED BULL RACING HONDA",
        date: "17 Mar 2019",
        racePosition: 3,
        PTS: 15,
      },
      {
        grandPrix: "China",
        team: "RED BULL RACING HONDA",
        date: "14 Apr 2019",
        racePosition: 4,
        PTS: 12,
      },
      {
        grandPrix: "Russia",
        team: "RED BULL RACING HONDA",
        date: "30 Sep 2018",
        racePosition: 5,
        PTS: 10,
      },
      {
        grandPrix: "Japan",
        team: "RED BULL RACING HONDA",
        date: "07 Oct 2018",
        racePosition: 3,
        PTS: 15,
      },
      {
        grandPrix: "Russia",
        team: "	RED BULL RACING TAG HEUER",
        date: "30 Apr 2017",
        racePosition: 5,
        PTS: 10,
      },
      {
        grandPrix: "Spain",
        team: "	RED BULL RACING TAG HEUER",
        date: "14 May 2017",
        racePosition: "DNF",
        PTS: 0,
      },
    ],
  },
  {
    name: "Lewis Hamilton",
    nationality: "GBR",
    matchs: [
      {
        grandPrix: "Bahrain",
        team: "MERCEDES",
        date: "05 Mar 2023",
        racePosition: 5,
        PTS: 10,
      },
      {
        grandPrix: "Saudi Arabia",
        team: "MERCEDES",
        date: "19 Mar 2023",
        racePosition: 5,
        PTS: 10,
      },
      {
        grandPrix: "Australia",
        team: "MERCEDES",
        date: "02 Apr 2023",
        racePosition: 2,
        PTS: 18,
      },
      {
        grandPrix: "Azerbaijan",
        team: "MERCEDES",
        date: "30 Apr 2023",
        racePosition: 6,
        PTS: 10,
      },
      {
        grandPrix: "Miami",
        team: "MERCEDES",
        date: "07 May 2023",
        racePosition: 6,
        PTS: 8,
      },
      {
        grandPrix: "Monaco",
        team: "MERCEDES",
        date: "28 May 2023",
        racePosition: 4,
        PTS: 13,
      },
      {
        grandPrix: "Spain",
        team: "MERCEDES",
        date: "04 Jun 2023",
        racePosition: 2,
        PTS: 18,
      },
      {
        grandPrix: "Bahrain",
        team: "MERCEDES",
        date: "20 Mar 2022",
        racePosition: 3,
        PTS: 15,
      },
      {
        grandPrix: "Saudi Arabia",
        team: "MERCEDES",
        date: "27 Mar 2022",
        racePosition: 10,
        PTS: 1,
      },
      {
        grandPrix: "Australia",
        team: "MERCEDES",
        date: "10 Apr 2022",
        racePosition: 4,
        PTS: 12,
      },
      {
        grandPrix: "Emilia Romagna",
        team: "MERCEDES",
        date: "24 Apr 2022",
        racePosition: 13,
        PTS: 0,
      },
      {
        grandPrix: "Turkey",
        team: "MERCEDES",
        date: "10 Oct 2021",
        racePosition: 5,
        PTS: 10,
      },
      {
        grandPrix: "United States",
        team: "MERCEDES",
        date: "24 Oct 2021",
        racePosition: 2,
        PTS: 19,
      },
      {
        grandPrix: "Mexico",
        team: "MERCEDES",
        date: "07 Nov 2021",
        racePosition: 2,
        PTS: 18,
      },
      {
        grandPrix: "Bahrain",
        team: "MERCEDES",
        date: "29 Nov 2020",
        racePosition: 1,
        PTS: 25,
      },
      {
        grandPrix: "Belgium",
        team: "MERCEDES",
        date: "30 Aug 2020",
        racePosition: 1,
        PTS: 25,
      },
      {
        grandPrix: "Australia",
        team: "MERCEDES",
        date: "17 Mar 2019",
        racePosition: 2,
        PTS: 18,
      },
      {
        grandPrix: "China",
        team: "MERCEDES",
        date: "14 Apr 2019",
        racePosition: 1,
        PTS: 25,
      },
      {
        grandPrix: "Russia",
        team: "MERCEDES",
        date: "30 Sep 2018",
        racePosition: 1,
        PTS: 25,
      },
      {
        grandPrix: "Japan",
        team: "MERCEDES",
        date: "07 Oct 2018",
        racePosition: 1,
        PTS: 25,
      },
      {
        grandPrix: "Russia",
        team: "	RED BULL RACING TAG HEUER",
        date: "30 Apr 2017",
        racePosition: 3,
        PTS: 12,
      },
      {
        grandPrix: "Spain",
        team: "	RED BULL RACING TAG HEUER",
        date: "14 May 2017",
        racePosition: 1,
        PTS: 25,
      },
    ],
  },
  {
    name: "Carlos Sainz",
    nationality: "ESP",
    matchs: [
      {
        grandPrix: "Bahrain",
        team: "FERRARI",
        date: "05 Mar 2023",
        racePosition: 4,
        PTS: 12,
      },
      {
        grandPrix: "Saudi Arabia",
        team: "FERRARI",
        date: "19 Mar 2023",
        racePosition: 6,
        PTS: 8,
      },
      {
        grandPrix: "Australia",
        team: "FERRARI",
        date: "02 Apr 2023",
        racePosition: 12,
        PTS: 0,
      },
      {
        grandPrix: "Azerbaijan",
        team: "FERRARI",
        date: "30 Apr 2023",
        racePosition: 5,
        PTS: 14,
      },
      {
        grandPrix: "Miami",
        team: "FERRARI",
        date: "07 May 2023",
        racePosition: 5,
        PTS: 10,
      },
      {
        grandPrix: "Monaco",
        team: "FERRARI",
        date: "28 May 2023",
        racePosition: 8,
        PTS: 4,
      },
      {
        grandPrix: "Spain",
        team: "FERRARI",
        date: "04 Jun 2023",
        racePosition: 5,
        PTS: 10,
      },
      {
        grandPrix: "Bahrain",
        team: "FERRARI",
        date: "20 Mar 2022",
        racePosition: 2,
        PTS: 18,
      },
      {
        grandPrix: "Saudi Arabia",
        team: "FERRARI",
        date: "27 Mar 2022",
        racePosition: 3,
        PTS: 15,
      },
      {
        grandPrix: "Australia",
        team: "FERRARI",
        date: "10 Apr 2022",
        racePosition: "DNF",
        PTS: 0,
      },
      {
        grandPrix: "Emilia Romagna",
        team: "FERRARI",
        date: "24 Apr 2022",
        racePosition: "DNF",
        PTS: 5,
      },
      {
        grandPrix: "Turkey",
        team: "FERRARI",
        date: "10 Oct 2021",
        racePosition: 8,
        PTS: 4,
      },
      {
        grandPrix: "United States",
        team: "FERRARI",
        date: "24 Oct 2021",
        racePosition: 7,
        PTS: 6,
      },
      {
        grandPrix: "Mexico",
        team: "FERRARI",
        date: "07 Nov 2021",
        racePosition: 6,
        PTS: 8,
      },
      {
        grandPrix: "Bahrain",
        team: "MCLAREN RENAULT",
        date: "29 Nov 2020",
        racePosition: 5,
        PTS: 10,
      },
      {
        grandPrix: "Belgium",
        team: "MCLAREN RENAULT",
        date: "30 Aug 2020",
        racePosition: "DNF",
        PTS: 0,
      },
      {
        grandPrix: "Australia",
        team: "MCLAREN RENAULT",
        date: "17 Mar 2019",
        racePosition: "DNF",
        PTS: 0,
      },
      {
        grandPrix: "China",
        team: "MCLAREN RENAULT",
        date: "14 Apr 2019",
        racePosition: 14,
        PTS: 0,
      },
      {
        grandPrix: "Russia",
        team: "RENAULT",
        date: "30 Sep 2018",
        racePosition: 17,
        PTS: 0,
      },
      {
        grandPrix: "Japan",
        team: "RENAULT",
        date: "07 Oct 2018",
        racePosition: 10,
        PTS: 1,
      },
      {
        grandPrix: "Russia",
        team: "TORO ROSSO",
        date: "30 Apr 2017",
        racePosition: 10,
        PTS: 1,
      },
      {
        grandPrix: "Spain",
        team: "TORO ROSSO",
        date: "14 May 2017",
        racePosition: 7,
        PTS: 6,
      },
    ],
  },
  {
    name: "Sergio Perez",
    nationality: "MEX",
    matchs: [
      {
        grandPrix: "Bahrain",
        team: "RED BULL RACING HONDA RBPT",
        date: "05 Mar 2023",
        racePosition: 2,
        PTS: 18,
      },
      {
        grandPrix: "Saudi Arabia",
        team: "RED BULL RACING HONDA RBPT",
        date: "19 Mar 2023",
        racePosition: 1,
        PTS: 25,
      },
      {
        grandPrix: "Australia",
        team: "RED BULL RACING HONDA RBPT",
        date: "02 Apr 2023",
        racePosition: 5,
        PTS: 11,
      },
      {
        grandPrix: "Azerbaijan",
        team: "RED BULL RACING HONDA RBPT",
        date: "30 Apr 2023",
        racePosition: 1,
        PTS: 33,
      },
      {
        grandPrix: "Miami",
        team: "RED BULL RACING HONDA RBPT",
        date: "07 May 2023",
        racePosition: 2,
        PTS: 18,
      },
      {
        grandPrix: "Monaco",
        team: "RED BULL RACING HONDA RBPT",
        date: "28 May 2023",
        racePosition: 16,
        PTS: 0,
      },
      {
        grandPrix: "Spain",
        team: "RED BULL RACING HONDA RBPT",
        date: "04 Jun 2023",
        racePosition: 4,
        PTS: 12,
      },
      {
        grandPrix: "Bahrain",
        team: "RED BULL RACING RBPT",
        date: "20 Mar 2022",
        racePosition: "DNF",
        PTS: 0,
      },
      {
        grandPrix: "Saudi Arabia",
        team: "RED BULL RACING RBPT",
        date: "27 Mar 2022",
        racePosition: 4,
        PTS: 12,
      },
      {
        grandPrix: "Australia",
        team: "RED BULL RACING RBPT",
        date: "10 Apr 2022",
        racePosition: 2,
        PTS: 18,
      },
      {
        grandPrix: "Emilia Romagna",
        team: "RED BULL RACING RBPT",
        date: "24 Apr 2022",
        racePosition: 2,
        PTS: 24,
      },
      {
        grandPrix: "Turkey",
        team: "RED BULL RACING HONDA",
        date: "10 Oct 2021",
        racePosition: 3,
        PTS: 15,
      },
      {
        grandPrix: "United States",
        team: "RED BULL RACING HONDA",
        date: "24 Oct 2021",
        racePosition: 3,
        PTS: 15,
      },
      {
        grandPrix: "Mexico",
        team: "RED BULL RACING HONDA",
        date: "07 Nov 2021",
        racePosition: 3,
        PTS: 15,
      },
      {
        grandPrix: "Bahrain",
        team: "RACING POINT BWT MERCEDES",
        date: "29 Nov 2020",
        racePosition: "DNF",
        PTS: 0,
      },
      {
        grandPrix: "Belgium",
        team: "RACING POINT BWT MERCEDES",
        date: "30 Aug 2020",
        racePosition: 10,
        PTS: 1,
      },
      {
        grandPrix: "Australia",
        team: "RACING POINT BWT MERCEDES",
        date: "17 Mar 2019",
        racePosition: 13,
        PTS: 0,
      },
      {
        grandPrix: "China",
        team: "RACING POINT BWT MERCEDES",
        date: "14 Apr 2019",
        racePosition: 8,
        PTS: 4,
      },
      {
        grandPrix: "Russia",
        team: "FORCE INDIA MERCEDES",
        date: "30 Sep 2018",
        racePosition: 10,
        PTS: 1,
      },
      {
        grandPrix: "Japan",
        team: "FORCE INDIA MERCEDES",
        date: "07 Oct 2018",
        racePosition: 7,
        PTS: 6,
      },
      {
        grandPrix: "Russia",
        team: "FORCE INDIA MERCEDES",
        date: "30 Apr 2017",
        racePosition: 6,
        PTS: 8,
      },
      {
        grandPrix: "Spain",
        team: "FORCE INDIA MERCEDES",
        date: "14 May 2017",
        racePosition: 4,
        PTS: 12,
      },
    ],
  },
];

export const Teams = [
  {
    team: "RED BULL RACING HONDA",
    PTS: [287, 759, 585.5, 319, 417, 419, 368],
  },
  {
    team: "MERCEDES",
    PTS: [152, 515, 613.5, 573, 739, 655, 668],
  },
  {
    team: "FERRARI",
    PTS: [100, 554, 323.5, 131, 504, 571, 522],
  },
  {
    team: "MCLAREN MERCEDES",
    PTS: [17, 159, 275, 202, 145, 62, 30],
  },
  {
    team: "ALPINE RENAULT",
    PTS: [40, 173, 155, 181, 91, 122, 57],
  },
  {
    team: "ALPHATAURI HONDA RBPT",
    PTS: [2, 35, 142, 107, 85, 33, 53],
  },
  {
    team: "ASTON MARTIN ARAMCO MERCEDES",
    PTS: [134, 55, 77, 195, 73, 52, 187],
  },
  {
    team: "WILLIAMS MERCEDES",
    PTS: [1, 8, 23, 0, 1, 7, 83],
  },
  {
    team: "ALFA ROMEO FERRARI",
    PTS: [8, 55, 13, 8, 57, 48, 5],
  },
  {
    team: "HAAS FERRARI",
    PTS: [8, 37, 0, 3, 28, 93, 47],
  },
];
